export default CommentTestData = [
  {
    id: 0,
    nickname: '김민균',
    content: '레몬 새콤달콤',
    writerVote: 1,
    userLike: 25,
    userDislike: 15,
    like: false,
    dislike: false,
  },
  {
    id: 1,
    nickname: '이도엽',
    content: '복숭아 새콤달콤',
    writerVote: 2,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
  {
    id: 2,
    nickname: '이보나',
    content: '수박 새콤달콤',
    writerVote: 1,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
  {
    id: 3,
    nickname: '이승연',
    content: '딸기 새콤달콤',
    writerVote: 2,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
  {
    id: 4,
    nickname: '이재순',
    content: '블루베리 새콤달콤',
    writerVote: 1,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
];
