export default CommentTestData = [
  {
    id: 0,
    nickname: '김깻잎',
    content: '배고프다',
    writerVote: 1,
    userLike: 25,
    userDislike: 15,
    like: false,
    dislike: false,
  },
  {
    id: 1,
    nickname: '박깻잎',
    content: '배고프다1',
    writerVote: 2,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
  {
    id: 2,
    nickname: '이깻잎',
    content: '배고프다2',
    writerVote: 1,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
  {
    id: 3,
    nickname: '전깻잎',
    content: '배고프다3',
    writerVote: 2,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
  {
    id: 4,
    nickname: '한깻잎',
    content: '배고프다4',
    writerVote: 1,
    userLike: 25,
    userDislike: 10,
    like: false,
    dislike: false,
  },
];
