import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  button: {
    marginBottom: '5%',
    width: '23%',
    color: '#FFFFFF',
    height: '21%',
    backgroundColor: '#808080',
    borderRadius: 6,
    justifyContent: 'center',
  },
  button2: {
    marginBottom: '5%',
    width: '40%',
    color: '#FFFFFF',
    height: '30%',
    backgroundColor: '#808080',
    borderRadius: 6,
    justifyContent: 'center',
  },
  checkButton: {
    marginBottom: '5%',
    width: '23%',
    color: '#FFFFFF',
    height: '21%',
    backgroundColor: '#FF7171',
    borderRadius: 6,
    justifyContent: 'center',
  },
  checkButton2: {
    marginBottom: '5%',
    width: '40%',
    color: '#FFFFFF',
    height: '30%',
    backgroundColor: '#FF7171',
    borderRadius: 6,
    justifyContent: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'Bold',
    textAlign: 'center',
    fontSize: 15,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: '1%',
    paddingHorizontal: '5%',
    backgroundColor: '#FFFFFF',
  },
  focusInput: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    paddingVertical: 0,
    paddingHorizontal: '2%',
    height: '100%',
    borderRadius: 4,
    borderWidth: 1.5,
  },
  blurInput: {
    width: '100%',
    borderColor: '#808080',
    paddingVertical: 0,
    paddingHorizontal: '2%',
    height: '100%',
    borderRadius: 4,
    borderWidth: 1,
  },
  focusHalfInput: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    paddingVertical: 0,
    paddingHorizontal: '4%',
    height: '100%',
    borderRadius: 4,
    borderWidth: 1.5,
  },
  blurHalfInput: {
    width: '100%',
    borderColor: '#808080',
    paddingVertical: 0,
    paddingHorizontal: '4%',
    height: '100%',
    borderRadius: 4,
    borderWidth: 1,
  },
  checkFocusInput: {
    width: '75%',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    paddingVertical: 0,
    paddingHorizontal: '2%',
    height: '100%',
    borderRadius: 4,
    borderWidth: 1.5,
  },
  checkBlurInput: {
    width: '75%',
    borderColor: '#808080',
    height: '100%',
    paddingVertical: 0,
    paddingHorizontal: '2%',
    borderRadius: 4,
    borderWidth: 1,
  },
  confirmFalseButton: {
    paddingVertical: '1%',
    height: '100%',
    borderRadius: 6,
    backgroundColor: '#808080',
    marginHorizontal: '3%',
    width: '22%',
  },
  confirmTrueButton: {
    paddingVertical: '1%',
    height: '100%',
    borderRadius: 6,
    backgroundColor: '#FF7171',
    marginHorizontal: '3%',
    width: '22%',
  },
  confirmText: {
    textAlign: 'center',
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  errorText: {
    color: '#FF7171',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: '1%',
    marginVertical: 2,
  },
  checkBoxText: {
    textAlignVertical: 'center',
    fontSize: 12,
    paddingBottom: 1,
    color: '#000000',
  },
  dropDownOpen: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 6,
    borderColor: '#808080',
  },
  dropDownButton: {
    width: '75%',
    height: 30,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 6,
    borderColor: '#808080',
  },
});
export default styles;
